map_update_interval: 2.0
maxUrange: 4.0
minimumScore: 100
linearUpdate: 0.2
angularUpdate: 0.2
temporalUpdate: 0.5
delta: 0.05
lskip: 0
particles: 120
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
resampleThreshold: 0.5
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005